apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podcast-helm.fullname" . }}
  labels:
    {{- include "podcast-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "podcast-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "podcast-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "podcast-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: {{ .Values.initContainers.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        ports:
        - containerPort: {{ .Values.initContainers.ports.containerPort }}
        env:
          - name: DB_DATABASE
            value: {{ .Values.initContainers.env.DB_DATABASE  }}
          - name: DB_HOST
            value: {{ .Values.initContainers.env.DB_HOST  }}
          - name: DB_PASSWORD
            value:  {{ .Values.initContainers.env.DB_PASSWORD  }}
          - name: DB_PORT
            value:  {{ .Values.initContainers.env.DB_PORT  | quote }}
          - name: DB_USERNAME
            value: {{ .Values.initContainers.env.DB_USERNAME }}
        command: ["/bin/sh", "-c"]
        args: ["php artisan migrate --force"]
      containers:
      - env:
          - name: DB_DATABASE
            value: {{ .Values.initContainers.env.DB_DATABASE }}
          - name: DB_HOST
            value: {{ .Values.initContainers.env.DB_HOST }}
          - name: DB_PASSWORD
            value:  {{ .Values.initContainers.env.DB_PASSWORD }}
          - name: DB_PORT
            value:  {{ .Values.initContainers.env.DB_PORT | quote }}
          - name: DB_USERNAME
            value: {{ .Values.initContainers.env.DB_USERNAME }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        name: {{ .Chart.Name }}
        ports:
          - containerPort: {{ .Values.initContainers.ports.containerPort }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
            {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
